### ISSUE TITLE
Provide the code list dumps in RDF/Turtle

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#1]
Please provide the code list dumps in [RDF/Turtle](http://www.w3.org/TR/turtle/) serialization. The RDF/XML currently available in the repository is hard to read for people.

**Comment by skarampatakis** [comment]
TTL formatted files added as suggested.

**Comment by jindrichmynarz** [comment]
`kae-*` code lists are not available in Turtle.

**Comment by skarampatakis** [comment]
Every file uploaded in .ttl format. Please check if everything is ok.

**Comment by jindrichmynarz** [comment]
This issue is fixed.
