### ISSUE TITLE
Placeholder namespace 127.0.0.1:3333 in code lists from OpenRefine

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#10]
The code lists transformed via OpenRefine use its default placeholder namespace `127.0.0.1:3333`. This should be changed to a proper OpenBudgets.eu namespace.

**Comment by skarampatakis** [comment]
Corrected.

**Comment by jindrichmynarz** [comment]
The default placeholder namespace is still used in kae-esodon and kae-exodon.

**Comment by skarampatakis** [comment]
Files was not updated by mistake. Thank you for the notice. Please check if everything is ok.

**Comment by jindrichmynarz** [comment]
This issue is fixed.
