### ISSUE TITLE
No instances of skos:ConceptScheme

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#11]
All the produced miss instances of `skos:ConceptScheme` describing the code list. At least the `skos:ConceptScheme` instantiation along with a `rdfs:label` should be provided for each code list.

**Comment by skarampatakis** [comment]
Added for every code list. Please check if everything is as opposed to.

**Comment by jindrichmynarz** [comment]
`skos:ConceptScheme` is missing in the code lists Currency, kae-esodon, kae-exodon, and kae-ota.

**Comment by skarampatakis** [comment]
'skos:ConceptScheme' added for every codelist we trasformed. Please check if everything is ok.

**Comment by jindrichmynarz** [comment]
The issue is fixed.
