### ISSUE TITLE
All data in kae-exodon merged into a single skos:Concept

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#12]
All data in the kae-exodon code list is merged into a single instance of `skos:Concept` `<http://127.0.0.1:3333/Κ.Α.Ε>`. This seems to be a URI construction problem.

**Comment by skarampatakis** [comment]
Problem corrected. Please check if everything is ok so i can close the issue.

**Comment by jindrichmynarz** [comment]
The issue is fixed.
