### ISSUE TITLE
kae-ota: multiple skos:prefLabels per concept

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#14]
In the kae-ota code list, there are multiple values of `skos:prefLabel` per concept. The values are not distinguished via language tag, which makes this violate the [integrity constraint S14](http://www.w3.org/TR/skos-reference/#S14) from the SKOS specification.

**Comment by skarampatakis** [comment]
Problem corrected. Please check if everything is ok.

**Comment by jindrichmynarz** [comment]
If you run this query:

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept
WHERE {
  ?concept skos:prefLabel ?prefLabel .
}
GROUP BY ?concept
HAVING (COUNT(?prefLabel) > 1)
```

You will find out that the concepts `<http://data.openbudgets.eu/resource/codelist/kaeota/20.641>` still has multiple `skos:prefLabel`s.

**Comment by skarampatakis** [comment]
Corrected.

**Comment by jindrichmynarz** [comment]
This issue is fixed.
