### ISSUE TITLE
Invalid labelling property of skos:ConceptSchemes

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#16]
The code lists _CPC_, _CPA_, _CL-GEO_, _ESA2010 transactions in products_, _ESA2010 other changes in assets_, _ESA2010 non-financial assets_, _ESA2010 institutional sectors_, _ESA2010 financial assets_, _ESA2010 distributive transactions_, _ESA2010 balancing items and net worth_ and _ESA2010 assets and liabilities_ contain `skos:ConceptScheme` labelled using `skos:prefLabel`. Since the `rdfs:domain` of `skos:prefLabel` is `skos:Concept` and `skos:ConceptScheme` is disjoint with `skos:Concept` ([integrity condition S9](http://www.w3.org/TR/skos-reference/#S9)), this is invalid. Please use `rdfs:label` as the labelling property for `skos:ConceptScheme`.

**Comment by skarampatakis** [comment]
Corrected.
