### ISSUE TITLE
skos:notations shouldn't have a language tag

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#19]
Several code lists (such as SITC) use language tags for objects of `skos:notation`; e.g., `"001.22"@en`. Since the code are not in a natural language, no language code should be used. Moreover, using a plain literal would simplify querying.

**Comment by skarampatakis** [comment]
SITC, PRODCOM and austrian version of NACE, OANACE, where corrected. Is there any other codelist that you noticed the same problem?

**Comment by jindrichmynarz** [comment]
`skos:notation`s with language tags still appear in these code lists:
- estructura_economica_g_aragon_2013
- estructura_financiacion_i_aragon_2013
