### ISSUE TITLE
Trailing slashes in the IRIs of KAE code lists

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#23]
`skos:ConceptScheme`s in KAE code lists are identified with IRI containing trailing slashes:
- [KAE Exodon](https://github.com/openbudgets/Code-lists/blob/master/OpenRefine/kae-exodon/KAE-EXODON2015.ttl): `<http://data.openbudgets.eu/resource/codelist/kaexodon/>`
- [KAE Esodon](https://github.com/openbudgets/Code-lists/blob/master/OpenRefine/kae-esodon/kae-esodon.ttl): `<http://data.openbudgets.eu/resource/codelist/kaesodon/>`
- [KAE Ota](https://github.com/openbudgets/Code-lists/blob/master/OpenRefine/kae-ota/KAE_OTA_2014.ttl): `<http://data.openbudgets.eu/resource/codelist/kaeota/>`

It would be better if the trailing slashes were dropped.

**Comment by skarampatakis** [comment]
Actually these are outdated versions that was transformed only to showcase how to transform the codelists using OpenRefine. 

Current Greek datasets use the codelists from [this](https://github.com/openbudgets/Code-lists/tree/master/UnifiedViews/skosified/kae) folder.
