### ISSUE TITLE
TriG files are the same as Turtle files

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#26]
I noticed the TriG files in [EU categorization](https://github.com/openbudgets/Code-lists/tree/master/EUcategorization) and [countries' operational programmes](https://github.com/openbudgets/Code-lists/tree/master/CountriesOperationalProgrammes) are the same as the Turtle files. While this is syntactically valid TriG, it is redundant. TriG files would need to have the Turtle content wrapped in named graphs; as in `<named-graph> { ... Turtle content ... }`.

**Comment by OndrejZamazal** [comment]
Thanks for the hint. I changed TriG files and removed Turtle files.
