### ISSUE TITLE
Codelists appearing twice

### ISSUE THREAD

**Issue by larjohn** [openbudgets/Code-lists#27]
There is this query:
```


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>

SELECT ?binding_a062e_19056 ?g WHERE {
GRAPH ?g{
	<http://data.openbudgets.eu/resource/dataset/greek-municipalities/codelist/athens-administrations/1> <http://www.w3.org/2004/02/skos/core#prefLabel> ?binding_a062e_19056 .
	}
	
}
LIMIT 100


```

that shows the same code list has been uploaded twice. This leads to duplicate results if no GRAPH is selected or DISTINCT is not used. 

What is the recommended way to resolve this optimally (DISTINCT is not optimal, by experience)

**Comment by skarampatakis** [comment]
The original codelist is in the graph http://data.openbudgets.eu/resource/dataset/greek-municipalities/codelist/athens-administrations. 

For some reason there seems to be graphs for every instance of this Scheme, with only one instance per graph, and graph name the very same instance IRI. So I think the best approach is to just delete them. And find how these were created and if this happens to other codelists or resources in general.

**Comment by skarampatakis** [comment]
I found these [graphs](http://data.openbudgets.eu/sparql?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+qb%3A+%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+xro%3A+%3Chttp%3A%2F%2Fpurl.org%2Fxro%2Fns%23%3E%0D%0A%0D%0ASELECT+distinct+%3Fg+WHERE+%7B%0D%0AGRAPH+%3Fg+%7B%0D%0A%09%3Fs+%3Fp+%3Flabel+.%0D%0A%09%7D%0D%0A%09%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)

with this query
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>

SELECT distinct ?g WHERE {
GRAPH ?g {
	?s ?p ?label .
	}
	
}
```

So it seems that for some reason there are graphs containing just on skos:Concept. This happens for one Bonn codelist, the one mentioned earlier and the functional classification of Thessaloniki 2016 at least. So we could just delete graphs whose name is not the same as the ConceptScheme they are referring to. And find how these were created.
