### ISSUE TITLE
Language tags should be omitted for values of skos:notation

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#3]
The code lists use language tags for values of `skos:notation`. For example:

```
<http://data.openbudgets.eu/resource/ESA2010_assets_and_liabilities/F.1> skos:notation "F.1"@en .
```

Since notations are not specific for any language, the language tags should be removed.

**Comment by skarampatakis** [comment]
Language tags removed for values of skos:notation.
