### ISSUE TITLE
Code lists fail quality checks

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#4]
If I run [qSKOS](https://github.com/cmader/qSKOS/) on NACE, it reports several errors that might indicate errors in data transformation, such as:

* Orphan Concepts: FAIL (2)
* Disconnected Concept Clusters: FAIL (10)
* Undefined SKOS Resources: FAIL (1)

Please run qSKOS on the produced code lists to ensure they meet basic quality checks.

**Comment by skarampatakis** [comment]
Should i close this one?

**Comment by jindrichmynarz** [comment]
Have you run qSKOS without any errors reported?

**Comment by skarampatakis** [comment]
We have run qSKOS for every codelist we transformed. In most codelists there aren't any issu except from missig out links fail which is ok and undocumented fail which is also ok. For some of them may be some issues but this isn't a problem of the conversion but of the quality of the codelist. So i think we could close this issue.

**Comment by jindrichmynarz** [comment]
OK, great!
