### ISSUE TITLE
Currency code list is not in SKOS

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#5]
Currency code list is not represented using SKOS. Instead, it uses a custom vocabulary. It should be represented using SKOS as the other code lists. If there is data that cannot be expressed with SKOS, then an additional vocabulary should be used.

**Comment by skarampatakis** [comment]
Currency code list is now on SKOS. Entity data is expressed as skos:notation literal value for later use. We could also use dbp:currency property from DBpedia ontology, if this is preferable. Please leave your comments.

**Comment by jindrichmynarz** [comment]
There are several issues with the SKOS representation.
1. There are multiple `skos:notation`s per `skos:Concept`. For example:

```
<http://data.openbudgets.eu/codelist/currency/EUR> <http://www.w3.org/2004/02/skos/core#notation> "2" , "?LAND ISLANDS" , "ANDORRA" , "AUSTRIA" , "BELGIUM" ,  "CYPRUS" , "ESTONIA" , "EUROPEAN UNION" , "FINLAND" , "FRANCE" , "FRENCH GUIANA" , "FRENCH SOUTHERN TERRITORIES    (THE)" , "GERMANY" , "GREECE" , "GUADELOUPE" , "HOLY SEE (THE)" , "IRELAND" , "ITALY" , "LATVIA" , "LITHUANIA" ,   "LUXEMBOURG" , "MALTA" , "MARTINIQUE" , "MAYOTTE" , "MONACO" , "MONTENEGRO" , "NETHERLANDS (THE)" , "PORTUGAL" ,  "R?UNION" , "SAINT BARTH?LEMY" , "SAINT MARTIN (FRENCH PART)" , "SAINT PIERRE AND MIQUELON" , "SAN MARINO" ,  "SLOVAKIA" , "SLOVENIA" , "SPAIN" .
```
1. Objects of `skos:altLabel` seem more appropriate as objects of `skos:notation` (e.g., `skos:altLabel "EUR"@en` for the above example would be better as `skos:notation "EUR"`).
2. There seems to be a problem with encoding of non-ASCII characters. For example, Åland Islands are labelled as "?LAND ISLANDS" and Réunion is labelled as "R?UNION".
3. `skos:inScheme` and `skos:topConceptOf` links are missing.

**Comment by skarampatakis** [comment]
Could you please check this list again. We have made some changes according to your suggestions.

**Comment by jindrichmynarz** [comment]
It seems that some of the issues are resolved. However, I cannot find the labels for Åland Islands or Réunion to check if the character encoding problem is solved. Moreover, `skos:topConceptOf` links are still missing.

Also, why does each concept have `skos:note "2"en`?

**Comment by skarampatakis** [comment]
1. We decided to drop this data for now, as there is not proper property. We found a proper one from dbpedia ontology, `dbp:currency`, but this requires a country code list to be linked to because is a relation property link .  
2. Because there are not any child nodes so every currency entity could be a Top Concept. 'skos:inScheme' was added instead of 'skos:topConceptOf' which is sub-property of 'skos:inScheme'. If by your opinion this should be changed please let me know.
3. These are data from column minor unit temporally as there was not proper property.

**Comment by jindrichmynarz** [comment]
Ad 1: It seems that it constitutes a link from a region (a different code list) to currency. Indeed, `dbp:currency` looks like an appropriate property to use for this purpose.

Ad 2: I think it is fine if all concepts in a code lists are top concepts. It merely indicates that the code list does not have any hierarchical relations. I see no harm in adding `skos:topConceptOf` links.

Ad 3: What is a "minor unit"? If you want to capture this information and no existing property fits it, then define a new property.

**Comment by skarampatakis** [comment]
1. So, by your opinion should we do the linking? A region codelist in rdf format does not exist for now, so we shall transform one, or we could do the linking to the appropriate DBpedia entities. Another option is to keep this data in a "invented" property temporally so we could make the connections at a next stage.
2. 'skos:topConceptOf' links was added. please check.
3. We will drop this data as it seems with no meaning.

**Comment by jindrichmynarz** [comment]
Ad 1: This is ultimately up to you whether you see this effort are worthy of your time. Do you think these links can be used in the context of OpenBudgets.eu? If so, then working on a regions code list and linking it may be useful.

**Comment by skarampatakis** [comment]
Changed `rdf:type` to the correct one and also included the rdf external links to iso 3166 country list using the `dbp:currency` property from DBpedia ontology. Is it ok?

**Comment by jindrichmynarz** [comment]
What `rdf:type` have you added?

**Comment by skarampatakis** [comment]
Both `rdf:type` included as for completiness. 
`http://www.w3.org/2004/02/skos/core#Concept` 
`http://data.openbudgets.eu/ontology/Currency`

**Comment by jindrichmynarz** [comment]
OK, thanks for explaining. I think we can close this issue.
