### ISSUE TITLE
Currency code list contains invalid characters in URIs

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#6]
Currency code list contains invalid characters in URIs, such as whitespace. You can check by running [Apache Jena's Riot](https://jena.apache.org/documentation/io/) (`riot --validate currencies.rdf`). Whatever you put into URIs should be properly encoded. [URI slugs](http://patterns.dataincubator.org/book/url-slug.html) can be used to avoid these problems.

**Comment by skarampatakis** [comment]
Corrected. Using iso4217 alphabetic code plus namespace as entity name .
